services:
  serving:
    build:
      context: .
      target: serving-develop
    env_file:
      - .env
    user: "${UID}:${GID}"
    userns_mode: "host"
    volumes:
      - ./models:/models:z
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU_DEVICE}"]
              capabilities: [ gpu ]
    shm_size: 8GB

  develop:
    build:
      context: .
      target: util
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    userns_mode: "host"
    command: [ "sleep", "infinity" ]
    working_dir: /workspace/koina
    volumes:
      - .:/workspace/koina/:z
    env_file:
      - .env

  web:
    build:
      context: .
      target: web
      args:
        UID: ${UID}
        GID: ${GID}
    userns_mode: "host"
    ports:
      - 3000:3000
    volumes:
      - ./:/workspace/koina
    working_dir: /workspace/koina/web
    command: npm run dev
